---
on: push

name: Test SSH action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Remote command execution test
        uses: itk-dev/actions-remote-ssh@master
        with:
          command: |
            whoami
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          cert: ${{ secrets.PUBLIC_KEY_CERT }}
          args: "-tt"